from app.api.routes import (
    admin_alerts,
    admin_reporting,
    itmb_ws,
    management,
    multitenant,
    otp_forwarder,
    realtime,
    reports,
    rpa_phase1,
    system,
    user_reporting,
    waybill_entry,
    waybill_map,
)

__all__ = [
    "admin_alerts",
    "waybill_map",
    "waybill_entry",
    "management",
    "itmb_ws",
    "reports",
    "multitenant",
    "otp_forwarder",
    "rpa_phase1",
    "system",
    "realtime",
    "admin_reporting",
    "user_reporting",
]
