export enum QueueName {
  AUTH = 'auth',
  SUBMIT = 'submit',
  RETRY = 'retry',
  DEAD_LETTER = 'dead-letter'
}

export enum RetryTarget {
  AUTH = 'auth',
  SUBMIT = 'submit'
}

export enum JobFailureCode {
  SESSION_MISSING = 'SESSION_MISSING',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  CAPTCHA_PROVIDER_DOWN = 'CAPTCHA_PROVIDER_DOWN',
  CAPTCHA_SOLVE_FAILED = 'CAPTCHA_SOLVE_FAILED',
  LEGACY_AUTH_FAILED = 'LEGACY_AUTH_FAILED',
  LEGACY_RATE_LIMITED = 'LEGACY_RATE_LIMITED',
  LEGACY_VALIDATION_FAILED = 'LEGACY_VALIDATION_FAILED',
  LEGACY_SERVER_ERROR = 'LEGACY_SERVER_ERROR',
  PROXY_BANNED = 'PROXY_BANNED',
  UNKNOWN = 'UNKNOWN'
}
